/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLearnShadowReplayRouteImport } from './routes/api/learn/shadow-replay'
import { Route as ApiWatchHealthRouteImport } from './routes/api/watch/health'
import { Route as ApiWatchTickRouteImport } from './routes/api/watch/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearnShadowReplayRoute = ApiLearnShadowReplayRouteImport.update({
  id: '/api/learn/shadow-replay',
  path: '/api/learn/shadow-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchHealthRoute = ApiWatchHealthRouteImport.update({
  id: '/api/watch/health',
  path: '/api/watch/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchTickRoute = ApiWatchTickRouteImport.update({
  id: '/api/watch/tick',
  path: '/api/watch/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/learn/shadow-replay': typeof ApiLearnShadowReplayRoute
  '/api/watch/health': typeof ApiWatchHealthRoute
  '/api/watch/tick': typeof ApiWatchTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/learn/shadow-replay': typeof ApiLearnShadowReplayRoute
  '/api/watch/health': typeof ApiWatchHealthRoute
  '/api/watch/tick': typeof ApiWatchTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/learn/shadow-replay': typeof ApiLearnShadowReplayRoute
  '/api/watch/health': typeof ApiWatchHealthRoute
  '/api/watch/tick': typeof ApiWatchTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/learn/shadow-replay' | '/api/watch/health' | '/api/watch/tick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/learn/shadow-replay' | '/api/watch/health' | '/api/watch/tick'
  id: '__root__' | '/' | '/api/learn/shadow-replay' | '/api/watch/health' | '/api/watch/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLearnShadowReplayRoute: typeof ApiLearnShadowReplayRoute
  ApiWatchHealthRoute: typeof ApiWatchHealthRoute
  ApiWatchTickRoute: typeof ApiWatchTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/shadow-replay': {
      id: '/api/learn/shadow-replay'
      path: '/api/learn/shadow-replay'
      fullPath: '/api/learn/shadow-replay'
      preLoaderRoute: typeof ApiLearnShadowReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/health': {
      id: '/api/watch/health'
      path: '/api/watch/health'
      fullPath: '/api/watch/health'
      preLoaderRoute: typeof ApiWatchHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/tick': {
      id: '/api/watch/tick'
      path: '/api/watch/tick'
      fullPath: '/api/watch/tick'
      preLoaderRoute: typeof ApiWatchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLearnShadowReplayRoute: ApiLearnShadowReplayRoute,
  ApiWatchHealthRoute: ApiWatchHealthRoute,
  ApiWatchTickRoute: ApiWatchTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
