/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShadowActivosRouteImport } from './routes/shadow-activos'
import { Route as ShadowRadarRouteImport } from './routes/shadow-radar'
import { Route as ApiBotRouteImport } from './routes/api/bot'
import { Route as ApiLabV1StatsRouteImport } from './routes/api/lab/v1-stats'
import { Route as ApiLearnShadowReplayRouteImport } from './routes/api/learn/shadow-replay'
import { Route as ApiPaperCronRouteImport } from './routes/api/paper/cron'
import { Route as ApiPaperViewRouteImport } from './routes/api/paper/view'
import { Route as ApiShadowDiscoveryRouteImport } from './routes/api/shadow/discovery'
import { Route as ApiShadowDiscoveryExploreRouteImport } from './routes/api/shadow/discovery-explore'
import { Route as ApiShadowRadarRouteImport } from './routes/api/shadow/radar'
import { Route as ApiWatchHealthRouteImport } from './routes/api/watch/health'
import { Route as ApiWatchTickRouteImport } from './routes/api/watch/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowActivosRoute = ShadowActivosRouteImport.update({
  id: '/shadow-activos',
  path: '/shadow-activos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowRadarRoute = ShadowRadarRouteImport.update({
  id: '/shadow-radar',
  path: '/shadow-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotRoute = ApiBotRouteImport.update({
  id: '/api/bot',
  path: '/api/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabV1StatsRoute = ApiLabV1StatsRouteImport.update({
  id: '/api/lab/v1-stats',
  path: '/api/lab/v1-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearnShadowReplayRoute = ApiLearnShadowReplayRouteImport.update({
  id: '/api/learn/shadow-replay',
  path: '/api/learn/shadow-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperCronRoute = ApiPaperCronRouteImport.update({
  id: '/api/paper/cron',
  path: '/api/paper/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperViewRoute = ApiPaperViewRouteImport.update({
  id: '/api/paper/view',
  path: '/api/paper/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShadowDiscoveryRoute = ApiShadowDiscoveryRouteImport.update({
  id: '/api/shadow/discovery',
  path: '/api/shadow/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShadowDiscoveryExploreRoute =
  ApiShadowDiscoveryExploreRouteImport.update({
    id: '/api/shadow/discovery-explore',
    path: '/api/shadow/discovery-explore',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShadowRadarRoute = ApiShadowRadarRouteImport.update({
  id: '/api/shadow/radar',
  path: '/api/shadow/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchHealthRoute = ApiWatchHealthRouteImport.update({
  id: '/api/watch/health',
  path: '/api/watch/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchTickRoute = ApiWatchTickRouteImport.update({
  id: '/api/watch/tick',
  path: '/api/watch/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shadow-activos': typeof ShadowActivosRoute
  '/shadow-radar': typeof ShadowRadarRoute
  '/api/bot': typeof ApiBotRoute
  '/api/lab/v1-stats': typeof ApiLabV1StatsRoute
  '/api/learn/shadow-replay': typeof ApiLearnShadowReplayRoute
  '/api/paper/cron': typeof ApiPaperCronRoute
  '/api/paper/view': typeof ApiPaperViewRoute
  '/api/shadow/discovery': typeof ApiShadowDiscoveryRoute
  '/api/shadow/discovery-explore': typeof ApiShadowDiscoveryExploreRoute
  '/api/shadow/radar': typeof ApiShadowRadarRoute
  '/api/watch/health': typeof ApiWatchHealthRoute
  '/api/watch/tick': typeof ApiWatchTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shadow-activos': typeof ShadowActivosRoute
  '/shadow-radar': typeof ShadowRadarRoute
  '/api/bot': typeof ApiBotRoute
  '/api/lab/v1-stats': typeof ApiLabV1StatsRoute
  '/api/learn/shadow-replay': typeof ApiLearnShadowReplayRoute
  '/api/paper/cron': typeof ApiPaperCronRoute
  '/api/paper/view': typeof ApiPaperViewRoute
  '/api/shadow/discovery': typeof ApiShadowDiscoveryRoute
  '/api/shadow/discovery-explore': typeof ApiShadowDiscoveryExploreRoute
  '/api/shadow/radar': typeof ApiShadowRadarRoute
  '/api/watch/health': typeof ApiWatchHealthRoute
  '/api/watch/tick': typeof ApiWatchTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shadow-activos': typeof ShadowActivosRoute
  '/shadow-radar': typeof ShadowRadarRoute
  '/api/bot': typeof ApiBotRoute
  '/api/lab/v1-stats': typeof ApiLabV1StatsRoute
  '/api/learn/shadow-replay': typeof ApiLearnShadowReplayRoute
  '/api/paper/cron': typeof ApiPaperCronRoute
  '/api/paper/view': typeof ApiPaperViewRoute
  '/api/shadow/discovery': typeof ApiShadowDiscoveryRoute
  '/api/shadow/discovery-explore': typeof ApiShadowDiscoveryExploreRoute
  '/api/shadow/radar': typeof ApiShadowRadarRoute
  '/api/watch/health': typeof ApiWatchHealthRoute
  '/api/watch/tick': typeof ApiWatchTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shadow-activos'
    | '/shadow-radar'
    | '/api/bot'
    | '/api/lab/v1-stats'
    | '/api/learn/shadow-replay'
    | '/api/paper/cron'
    | '/api/paper/view'
    | '/api/shadow/discovery'
    | '/api/shadow/discovery-explore'
    | '/api/shadow/radar'
    | '/api/watch/health'
    | '/api/watch/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shadow-activos'
    | '/shadow-radar'
    | '/api/bot'
    | '/api/lab/v1-stats'
    | '/api/learn/shadow-replay'
    | '/api/paper/cron'
    | '/api/paper/view'
    | '/api/shadow/discovery'
    | '/api/shadow/discovery-explore'
    | '/api/shadow/radar'
    | '/api/watch/health'
    | '/api/watch/tick'
  id:
    | '__root__'
    | '/'
    | '/shadow-activos'
    | '/shadow-radar'
    | '/api/bot'
    | '/api/lab/v1-stats'
    | '/api/learn/shadow-replay'
    | '/api/paper/cron'
    | '/api/paper/view'
    | '/api/shadow/discovery'
    | '/api/shadow/discovery-explore'
    | '/api/shadow/radar'
    | '/api/watch/health'
    | '/api/watch/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShadowActivosRoute: typeof ShadowActivosRoute
  ShadowRadarRoute: typeof ShadowRadarRoute
  ApiBotRoute: typeof ApiBotRoute
  ApiLabV1StatsRoute: typeof ApiLabV1StatsRoute
  ApiLearnShadowReplayRoute: typeof ApiLearnShadowReplayRoute
  ApiPaperCronRoute: typeof ApiPaperCronRoute
  ApiPaperViewRoute: typeof ApiPaperViewRoute
  ApiShadowDiscoveryRoute: typeof ApiShadowDiscoveryRoute
  ApiShadowDiscoveryExploreRoute: typeof ApiShadowDiscoveryExploreRoute
  ApiShadowRadarRoute: typeof ApiShadowRadarRoute
  ApiWatchHealthRoute: typeof ApiWatchHealthRoute
  ApiWatchTickRoute: typeof ApiWatchTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow-activos': {
      id: '/shadow-activos'
      path: '/shadow-activos'
      fullPath: '/shadow-activos'
      preLoaderRoute: typeof ShadowActivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow-radar': {
      id: '/shadow-radar'
      path: '/shadow-radar'
      fullPath: '/shadow-radar'
      preLoaderRoute: typeof ShadowRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot': {
      id: '/api/bot'
      path: '/api/bot'
      fullPath: '/api/bot'
      preLoaderRoute: typeof ApiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lab/v1-stats': {
      id: '/api/lab/v1-stats'
      path: '/api/lab/v1-stats'
      fullPath: '/api/lab/v1-stats'
      preLoaderRoute: typeof ApiLabV1StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/shadow-replay': {
      id: '/api/learn/shadow-replay'
      path: '/api/learn/shadow-replay'
      fullPath: '/api/learn/shadow-replay'
      preLoaderRoute: typeof ApiLearnShadowReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paper/cron': {
      id: '/api/paper/cron'
      path: '/api/paper/cron'
      fullPath: '/api/paper/cron'
      preLoaderRoute: typeof ApiPaperCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paper/view': {
      id: '/api/paper/view'
      path: '/api/paper/view'
      fullPath: '/api/paper/view'
      preLoaderRoute: typeof ApiPaperViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shadow/discovery': {
      id: '/api/shadow/discovery'
      path: '/api/shadow/discovery'
      fullPath: '/api/shadow/discovery'
      preLoaderRoute: typeof ApiShadowDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shadow/discovery-explore': {
      id: '/api/shadow/discovery-explore'
      path: '/api/shadow/discovery-explore'
      fullPath: '/api/shadow/discovery-explore'
      preLoaderRoute: typeof ApiShadowDiscoveryExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shadow/radar': {
      id: '/api/shadow/radar'
      path: '/api/shadow/radar'
      fullPath: '/api/shadow/radar'
      preLoaderRoute: typeof ApiShadowRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/health': {
      id: '/api/watch/health'
      path: '/api/watch/health'
      fullPath: '/api/watch/health'
      preLoaderRoute: typeof ApiWatchHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch/tick': {
      id: '/api/watch/tick'
      path: '/api/watch/tick'
      fullPath: '/api/watch/tick'
      preLoaderRoute: typeof ApiWatchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShadowActivosRoute: ShadowActivosRoute,
  ShadowRadarRoute: ShadowRadarRoute,
  ApiBotRoute: ApiBotRoute,
  ApiLabV1StatsRoute: ApiLabV1StatsRoute,
  ApiLearnShadowReplayRoute: ApiLearnShadowReplayRoute,
  ApiPaperCronRoute: ApiPaperCronRoute,
  ApiPaperViewRoute: ApiPaperViewRoute,
  ApiShadowDiscoveryRoute: ApiShadowDiscoveryRoute,
  ApiShadowDiscoveryExploreRoute: ApiShadowDiscoveryExploreRoute,
  ApiShadowRadarRoute: ApiShadowRadarRoute,
  ApiWatchHealthRoute: ApiWatchHealthRoute,
  ApiWatchTickRoute: ApiWatchTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
